### ISSUE TITLE
Formatting issue: An extra line and line feed is issued at the top of some buttons

### ISSUE THREAD

**Issue by GeneMosher** [ViewTouch/viewtouch#115]
An extra line and line feed is issued at the top of some pages after text headers are printed.  The bug can be seen when selecting the 'Displays & Tablets' button located at the right on Page One.  The button in this case displaying the unnecessary line is a Button Type 'Hardware'.

The bug can also be seen in another button on page -61, Revenue & Productivity Analysis Report, where Button Type 'Report' and Report Type 'System Balance' also displays this line.  (To see this, Select 13524 > Administration > Manager's Gateway > Reports > Revenue & Productivity.) The color of the extra line is always black and seems to be printed after any text is printed at the top of the buttons. Any lines at the top which are colored are OK.

The bug also shows on the remote kitchen and bar pages which are also located at the right on Page One if any menu items have been ordered.  The buttons on these pages are: Button Type 'Report', Report Type 'Check'.

**Comment by NeroBurner** [comment]
Is the following screenshot showing the Bug? If I understand right the space below the blue line and the black line should not be there?

![image](https://user-images.githubusercontent.com/9076163/103820329-7126f280-506c-11eb-9c4f-11c421669960.png)

another screenshot, but this time of the 'Displays & Tablets' view

![image](https://user-images.githubusercontent.com/9076163/103820551-da0e6a80-506c-11eb-96b8-5016ec3cd73e.png)
