### ISSUE TITLE
Add GitHub Actions for better CI integration

### ISSUE THREAD

**Issue by NeroBurner** [ViewTouch/viewtouch#122]
GitHub doesn't show travis-ci pipelines anymore (at least not for me). GitHub itself now provides CI capabilities with GitHub Actions

I think the Catch2 workflows could be a good reference to create Actions for ViewTouch

https://github.com/catchorg/Catch2/blob/devel/.github/workflows/linux-simple-builds.yml

as base image I suggest using `ubuntu-20.04` or maaaaaybe `ubuntu-latest`

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

I'd like to keep the explicit debian builds. For that we need to still use docker images

https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action

**Comment by GeneMosher** [comment]
Just WOW !!  New, exciting things for me to learn about.  I'll do my best to digest all this great new stuff and to update the info here at ViewTouch github to explain it to everyone as best as I can.  Thanks so very much !
