### ISSUE TITLE
Transfer of user data files in /usr/viewtouch/dat to another Raspberry Pi can cause a program failure

### ISSUE THREAD

**Issue by jcrafty** [ViewTouch/viewtouch#124]
Hope this proves useful to someone.  

Going from an Intel NUC to a Raspberry Pi 4.  

First discovery is that due to the variation in actual sizes of SD cards the 32G image file available to use for Raspberry Pi was 96 megs too big.  I ended up just imaging a 64G card.  I'm sure I could have somehow reduced the image size but didn't waste any time on that. 

Once Raspberry Pi was running and verified ViewTouch launched I copied the files from the NUC /dat/ folder to the Raspberry Pi.  

Launching ViewTouch now abruptly crashes just as the GUI is about to load with no indication in the log file as to what caused it.  

After systematically moving files over I discovered the issue was a **/dat/text/command.log** file which seems to have network settings specific to the NUC.  I deleted this file and ViewTouch now loads all the way into the GUI with all the settings, menus, etc where they should be.

**Comment by GeneMosher** [comment]
Thank you for this contribution !
