### ISSUE TITLE
AMA on reddit

### ISSUE THREAD

**Issue by GeneMosher** [ViewTouch/viewtouch#13]
This is not an issue but rather a heads up to everyone that I will be doing an AMA (ask me anything) on reddit on Sunday, November 13, at 3pm, Pacific Standard Time.  The URL for this is https://www.reddit.com/r/AMA/new/  I'll be online for three hours, until 6pm, Pacific Standard Time.

This AMA coincides with the 30th anniversary of when I first unveiled ViewTouch at the Comdex show in Las Vegas, on November 17, 1986.  I had just been married and my wife generously agreed to allow me to spend our honeymoon demonstrating ViewTouch to thousands of people during the five day show.  

Nicholas Turnbull has been working at a fever pitch for the past three weeks and in the next few days will be introducing several stability fixes and miscellaneous improvements into the ViewTouch code base here at GitHub.  I have a deep appreciation for Nicholas and for all who have made so many improvements and fixes in the code during the two years it's been at GitHub.  I especially am grateful to Nicholas for the step he has taken in using the Eclipse IDE and the GDB (Gnu Debugger).  After many visible and obvious bugs have been fixed in the past couple of years I regard it as quite a significant achievement, as would be expected, that Nicholas has been able to put the GDB to use and uncover some other bugs (serious, it turns out) which would certainly never have been discovered, much less fixed.  Special thanks to Nick for that, then.  And I hope that everyone who is not yet 100% committed to the use and value of GDB would take the cue from this.

I don't know of any other method to use GitHub to give everyone a heads up but if there is one I would appreciate being made wise to it so that I don't have to use the Issues component in the future to make announcements such as this one.

**Comment by pelya** [comment]
So you're saying that GDB has improved your codebase that much, I can only
imagine what will happen when you discover Valgrind.

**Comment by GeneMosher** [comment]
> So you're saying that GDB has improved your codebase that much, I can only
> imagine what will happen when you discover Valgrind.
Hi, Sergii! 

Well, I am pretty sure that Valgrind has been put to use already, but
remember, I'm not someone who writes code.  I just added a new page to
ViewTouch at GitHub and here's what I wrote.

/The recommended IDE for ViewTouch development is Eclipse.  The
recommended debugger for ViewTouch is GDB - the GNU Debugger. Eclipse
provides for a straightforward integration of GDB into Eclipse. I (Gene)
am not a developer except to the extent that I can use ViewTouch to
build and refine the ViewTouch GUI and restaurant menus so I have to
rely, in this case, on the following comments which Nicholas Turnbull
has previously written to me.//
//
//"I've found that of all the possible IDEs for reviewing and debugging
ViewTouch, Eclipse C++ Development Toolkit turns out to be ideal. I'd
been laboriously recompiling it via the command line and eventually it
just got too much of a drag. By adding the -g flag to the cmake build
file, setting Eclipse's build command to "make install" from the /build
directory and pointing the Run command to /usr/viewtouch/bin, it's
possible to actually both debug and install a live system interactively
with everything in the proper directories. The graphical interface to
gdb in Eclipse allows the precise object fields to be inspected and the
events traced, which is a huge help."//
//
//So, thanks Nick, for that. Now, my own comments again.  I would like
to think that with HiDef displays going for as little as $50-$60
everyone who is going to view/learn ViewTouch code can quite
effortlessly set up two HiDef displays so one display is running the
ViewTouch GUI and a second display is running Eclipse and GDB, providing
a view of the code execution simultaneously with the GUI.  I realize
that some will say, well duh, to this, but I also realize that others
are simply not doing this, so I have to ask anyone not doing this why on
earth they would not be doing this.  If it's a question of how to do it
then let's open an issue and provide a howto for such a setup, OK?//
/
The thing is that I can spot obvious bugs from the GUI but I cannot spot
any bug which is not obvious from the GUI, even though I do know from
clients that there is behavior which I cannot explain - and cannot
rectify on my own.  I therefore have to rely on someone who respects the
value of GDB and knows how to use it.  One other thing I know is that
many software developers simply do not use GDB or something like it, and
they do not use two displays so they can view code execution and
simultaneously view the GUI.  A third thing I know is that even though
the code compiles cleanly there are still bugs there which are never
going to be found by someone who does not respect, understand and use
GDB or something like it.  So I am really happy when someone like Nick,
who hasn't even been on board more than two weeks, steps forward and
fixes things that are broken, improves things that need improvement, and
understands that ViewTouch is something much more than a PoS program. 

There's a really bright future ahead for ViewTouch for several reasons
which are known only to me and that's quite something to say for a
software program that's 30 years old.  It's because of you, of Nicholas
Turnbull and because of many others that this is so, and as I approach
my 68th birthday in January I have to say that the only thing I want for
the rest of my life, whether it's 30 more years or 3 more years, is that
ViewTouch survives me and becomes something which the world at large
values.  Thanks again for everything, Sergii!

--Gene

**Comment by nicholasturnbull** [comment]
I must say that Gene is way too kind, and in fact I regret that I have had
less time to spend on this over the past few weeks than I'd anticipated.
The use of GDB in this case is quite facile - simply to allow
single-stepping and stepping into code in Eclipse, and object inspection on
the Eclipse GDB workbench. The VT code is quite complex in places and
arguably is in need of some serious refactoring, but our first priority
should be to fix the various reasons why it dies totally and unexpectedly.
I have perhaps done rather less than the way that Gene puts it, and have
been behind schedule with committing the code. The use of GDB, and Eclipse
for that matter, is perfectly standard. It has brought to light various
quite serious bugs throughout VT however that likely wouldn't have been
recognised without the use of a debugger.

Nevertheless, what I do see in ViewTouch is a tremendous scope for future
opportunity. VT solves many problems in the EPOS field that no other open
source POS does. Above all, however, the application itself can easily be
repurposed for a whole range of other tasks that are not POS systems but
are variations on a theme of similar functionality. This is, I feel, where
the real potential power of VT lies. It is an honour and a privilege to be
working on it.

Nick


*Nicholas J. Turnbull*
"Technology Therapist"
Consultant in Business Information Systems
Managing Director
nick@scimatix.com





*"To Reach the Unreachable Star"*
Empowering Businesses Through Technology

Consultancy Enquiries, Bookings and Technical Support
0333 567 1724 (1SCI) - 8.00am-6.30pm Monday-Friday

IT Emergency Callback Service (24-hour)
Dial 0333 567 9724 (9SCI)
and enter a phone number for an On-Call Advisor
to ring you back on. Retry after 30 minutes if no reply.

Scimatix Limited
9A Forum House, Stirling Road
Chichester, West Sussex
PO19 7DN United Kingdom

Scimatix Limited, registered in England and Wales no. 9910182. Registered
Office: Forum House, Stirling Road, Chichester, West Sussex, PO19 7DN, UK.
The contents of this e-mail are intended for the addressed recipient only
and may contain privileged information. Should you receive this e-mail in
error, please delete it. The views stated in this e-mail are those of the
author and do not necessarily express the opinion of Scimatix Limited upon
any matter. This message should not be construed as an offer of sale or
contract of any kind unless expressly indicated.

**Comment by nicholasturnbull** [comment]
Still working on it. I've decided to try to get the forking sorted out
before committing it as I think it's a bit of a killer (the terminal needs
to not unexpectedly die as an absolutely non-negotiable feature).

*Nicholas J. Turnbull*
"Technology Therapist"
Consultant in Business Information Systems
Managing Director
nick@scimatix.com





*"To Reach the Unreachable Star"*
Empowering Businesses Through Technology

Consultancy Enquiries, Bookings and Technical Support
0333 567 1724 (1SCI) - 8.00am-6.30pm Monday-Friday

IT Emergency Callback Service (24-hour)
Dial 0333 567 9724 (9SCI)
and enter a phone number for an On-Call Advisor
to ring you back on. Retry after 30 minutes if no reply.

Scimatix Limited
9A Forum House, Stirling Road
Chichester, West Sussex
PO19 7DN United Kingdom

Scimatix Limited, registered in England and Wales no. 9910182. Registered
Office: Forum House, Stirling Road, Chichester, West Sussex, PO19 7DN, UK.
The contents of this e-mail are intended for the addressed recipient only
and may contain privileged information. Should you receive this e-mail in
error, please delete it. The views stated in this e-mail are those of the
author and do not necessarily express the opinion of Scimatix Limited upon
any matter. This message should not be construed as an offer of sale or
contract of any kind unless expressly indicated.

**Comment by GeneMosher** [comment]
That's fine, of course, Nick.  I appreciate the fact that it's midnight
and you're still at it!  Thank you!

> Still working on it. I've decided to try to get the forking sorted out
> before committing it as I think it's a bit of a killer (the terminal needs
> to not unexpectedly die as an absolutely non-negotiable feature).
