### ISSUE TITLE
The screenshot at www.viewtouch.com/desktop.html does not load

### ISSUE THREAD

**Issue by rndtrash** [ViewTouch/viewtouch#137]
![image](https://github.com/user-attachments/assets/c2cb652c-f9d5-4588-b189-9f80f2c5a6c0)
![image](https://github.com/user-attachments/assets/93168272-ee70-4f49-b59d-3990bda7e0e9)
It seems you have accidentally embedded a local image :)

**Comment by GeneMosher** [comment]
OK, I have fixed this.  Thanks for pointing it out.

**Comment by GeneMosher** [comment]
Ivan, I would very much appreciate it if you would email me.  gene@viewtouch.com
