### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by GeneMosher** [ViewTouch/viewtouch#15]
[ 15%] Building CXX object CMakeFiles/vtpos.dir/loader/loader_main.cc.o
/home/viewtouch/viewtouch/loader/loader_main.cc: In function ‘void OpenStatusBox()’:
/home/viewtouch/viewtouch/loader/loader_main.cc:218:44: error: ‘gtk_label_set_xalign’ was not declared in this scope
     gtk_label_set_xalign(GTK_LABEL(label),0);
                                            ^
/home/viewtouch/viewtouch/loader/loader_main.cc:219:44: error: ‘gtk_label_set_yalign’ was not declared in this scope
     gtk_label_set_yalign(GTK_LABEL(label),1);
                                            ^

**Comment by NeroBurner** [comment]
this issue seems to be resolved, as viewtouch compiles successfully. Is there maybe a related commit fixing this issue?
