### ISSUE TITLE
xfonts-50dpi

### ISSUE THREAD

**Issue by mc4man** [ViewTouch/viewtouch#16]
You have this in the apt install command but it doesn't exist in either Debian or Ubuntu

**Comment by GeneMosher** [comment]
Your comment is a bit too brief for me to make sense of.  Can you elaborate?

**Comment by mc4man** [comment]
Sorry about that.
On this page - https://github.com/ViewTouch/viewtouch/wiki/Building
It says 
apt install xorg-dev libmotif-dev libfreetype6-dev cmake git xfonts-base xfonts-50dpi xfonts-100dpi
But there is no such package, at least in Debian or Ubuntu

**Comment by GeneMosher** [comment]
You are right. The problem is that I wrote 50 dpi fonts when I should have written 75 dpi fonts.  Those packages are all necessary and can be all installed properly after I make this correction, which I'll do right now.  Thanks for the heads up.  Any more help I can give, just let me know.

**Comment by mc4man** [comment]
Great, there was someone on Ubuntu forums looking for the 50 package. I figured I'd ask here for them..
