### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by NeroBurner** [ViewTouch/viewtouch#23]
Could someone with admin rights please enable this repo for travis-ci. I'd like to enable automatic build testing for a few platforms (Ubuntu and Debian Stretch) with others maybe following

Edit: direct link https://travis-ci.org/ViewTouch/viewtouch

**Comment by NeroBurner** [comment]
Is now enabled. Thanks

**Comment by GeneMosher** [comment]
With Pleasure, R !!
