### ISSUE TITLE
Wiki: link to pdf manual leads to empty directory

### ISSUE THREAD

**Issue by NeroBurner** [ViewTouch/viewtouch#24]
The Building wiki entry over at https://github.com/ViewTouch/viewtouch/wiki/Building has the following section

> A ViewTouch pdf user manual by Alex Underwood can be found at http://www.viewtouch.com/vt_manuals

But the link to the manual shows an empty folder. Is there still a pdf manual or should we remove the link?

**Comment by GeneMosher** [comment]
I've sent that document to you in a private email.  This document is available in the Raspberry Pi image.
