### ISSUE TITLE
blobfish.h defines unsigned int to be 32bit long

### ISSUE THREAD

**Issue by NeroBurner** [ViewTouch/viewtouch#25]
https://github.com/ViewTouch/viewtouch/blob/54b86a0fc74443d32e6b2272bd8155498a06c480/external/blowfish.h#L11-L12

this was true for 32bit linux, but is not true anymore for amd64 systems. I have no idea if this may lead to problems, but I'd like to document this flaw

To get a real 32bit unsigned int the `uint32_t` type from `stdint.h` can be used http://www.cplusplus.com/reference/cstdint/

As a side question: This header was introduced with C++11, is it OK to require newer C++ versions like C++11 or C++14 (or even C++17?)

**Comment by GeneMosher** [comment]
Please feel free to do that, yes, and I do support use of the C++17 standards.

**Comment by GeneMosher** [comment]
I have found Debian testing to be quite stable, especially the packages we use.
I did find [someone who is using GCC 8 to compile C++ 17](https://solarianprogrammer.com/2017/12/08/raspberry-pi-raspbian-install-gcc-compile-cpp-17-programs/) on Raspian so going with Debian testing and C++17 works for me.  In addition, Raspbian has been upgraded in the past few weeks.  I think that C++17 is important and I think that GCC8 is important, too, so if we can make GCC8 the default compiler then we should do that.
ViewTouch production systems are run on the Raspberry Pi featuring Raspbian so I don't think losing Ubuntu 16.04 (a long term support version) is a problem.     I don't actually know of anyone using Ubuntu in a production environment.  All of the clients/customers  I know of are using the RPi.

**Comment by NeroBurner** [comment]
Using a newer GCC than the one shipped with the distribution only works if the dependencies have pure C interfaces. If they have C++ interfaces the dependencies cannot be linked. We would have to compile those C++ libraries also with the same (newer) GCC
I don't know if this is the case for ViewTouch-dependencies. Just a heads-up

**Comment by GeneMosher** [comment]
I will, naturally, defer to your judgement on issues like this.  I am way outside my area of knowledge.  I will note that I'm running Debian Testing - aka Buster - on my own machine and GCC 8 is installed on my own machine, but I don't think my current cmake file is making use of it.  As always, my gratitude.

**Comment by NeroBurner** [comment]
you can inform cmake to use a specific compiler by setting the `CC` and `CXX` environment variables
I assume the full path to your GCC 8 binary is `/usr/local/bin/g++-8`. Then you can test on your local machine if using GCC 8 on debian buster works. Use with the following commands (in the root of the viewtouch repo:
```bash
export CC=/usr/local/bin/gcc-8
export CXX=/usr/local/bin/g++-8
cmake -H. -B_build_gcc8
cmake --buid _build_gcc8
```

Then one of the first lines of your cmake configure step should indicate the newer version
```
-- The C compiler identification is GNU 8.1.0
-- The CXX compiler identification is GNU 8.1.0
```

When the environment variable is not set, then cmake should use the default g++ installation (currently 7.3.0 on debian buster)
```
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
```

I'm not sure if you also have to set the CC variable to compile the pure C files (for example `blowfish.h`), but to be sure I'd set it anyways

**Comment by NeroBurner** [comment]
closed by removing blowfish.h and blowfish.c while removing the license checking code a4dc737d7bb0cb7441f1782ee0edace5e4795d49

@GeneMosher I'm still interested if compiling viewtouch with G++8 would work on debian buster (and maybe the raspberry). I hope you'll find the time to test it on your machine
