### ISSUE TITLE
Executable Descriptions

### ISSUE THREAD

**Issue by NeroBurner** [ViewTouch/viewtouch#36]
I'm trying to figure out what the executables are doing and how they can be used. 

### vt_cdu
connect to a printer? A touchscreen? What is a CDU

### vt_main
main thread. Can't directly start from command line, always exits

### vt_print
connect to a printer?

### vt_term
open a user terminal? GUI?

### vtpos
main binary, runs vt_main, opens GUI, only executable that stays open

is it possible to have a raspberry PI as central (headless) server and other devices with touchscreens (PC oas well as Android Devices) connect to the raspberry/server?
How are printers included into the system? Could you give me a high level overview on how a viewtouch system (with multiple endpoints and printers) is set up? I can't seem to figure out how viewtouch works (just schematic)

**Comment by GeneMosher** [comment]
vt_cdu     CDU = Customer Display Unit.  A display which customers can see.

vt_main  The decision was made a long time ago to use a loader to provide opportunities for checking things (is ViewTouch already running) and for passing arguments, such as -n (forcing ViewTouch to run without remote graphical terminals).

vt_print   Yep, the print routines.  Someone decided a long time ago that this should be a separate binary.

vt_term   Yep, remote graphical display/input sessions.  One program running many displays with touchscreen input is a touchscreen workgroup, which is what ViewTouch is all about.  This is the whole point of X, actually.  I support customers & clients by sometimes asking for a display/input session from their instance of ViewTouch.  I invoke this command in a terminal: `ssh -X viewtouch@remoteIP /usr/viewtouch/bin/openterm`

vtpos     Yes, keeps a terminal open for error messages

ViewTouch is designed for a single instance to run as many remote display/input sessions as one needs.  And each remote display/input session can have a printer, too.  The best way to envision this from the user's viewpoint is to go to the Administrative Matrix with the superuser logon, then look at all the pages there, especially the Configuration > Displays & Printers page.  This is where all the remote display/input ip addresses are entered, as well as any configuration options for each of them.  This is also where any printers with network interfaces on them are entered.  I will add some screenshots in the next day or two which make this a bit more clear.

**Comment by GeneMosher** [comment]
[]https://lh3.googleusercontent.com/-L3AofdxXEoc/W0hF-hGceaI/AAAAAAAAAv4/lqKF-deWJ_gsDpAWy35mgvUCwWUvaAdDgCL0BGAs/w530-d-h298-n/administrativeindex.png

**Comment by NeroBurner** [comment]
My goal is the following:
- the bar has a printer
- the kitchen has a printer
- there are no cash drawers
- waiters each have a smartphone/tablett and take orders
- depending on the type of the order (beverage or meal) the order is printed to the bar or the kitchen
- in the bar/kitchen one of the barman takes the printed order and prepares the drinks/meals
- other waiters without smartphones take the finished drinks from the bar to the customer (same thing with the meals from the kitchen)
- the waiters with smartphones (and a wallet) go to the tables and bill the customer, payment in cash

In this use case the only displays are the smartphones from the waiters. When everything is configured the main server does not need a display or can be controlled by another smartphone used by the superuser

Would this be possible with ViewTouch? What constraints would I face? Can I help to overcome those constraints?

I'd have to handle about 50 tables with ViewTouch. How does ViewTouch handle this many tables? Is there a way to group tables? Maybe by location (inside the bar, in the garden) or just number range (1-9, 10 to 19, 20 to 29, etc). Is there a way for a waiter to set custom location for just one order (for example "Gene Table near the bar")

Another question: how are the Android tablets connecting to the master server? I suspect it is not `ssh`. Does vtpos open a port to access the X server?

Sorry for asking so many questions. And thanks for your time and engagement :)
