### ISSUE TITLE
Obsolete Buildfiles

### ISSUE THREAD

**Issue by NeroBurner** [ViewTouch/viewtouch#37]
Can I remove build-configuration files from buildsystem than cmake? They are now obsolete and would need to be changed to work properly (Makefile, configure, netbeans project)

can we remove the [HELLO](https://github.com/ViewTouch/viewtouch/blob/master/HELLO) file?

can we remove some of the scrips in the [scripts](https://github.com/ViewTouch/viewtouch/tree/master/scripts) folder?

**Comment by GeneMosher** [comment]
I see no problem removing the three build-configuration files and the HELLO file.  I would have to know what individual scripts do to be able to offer an opinion of any of them.
