### ISSUE TITLE
tz needs timezone database

### ISSUE THREAD

**Issue by NeroBurner** [ViewTouch/viewtouch#58]
tz needs IANA timezone, this is provided by the `tzdata` package on Ubuntu. Otherwise `TimeInfo::Set()` throws an exception

- [x] update CI
  - [x] update Ubuntu Dockerfile to install package
  - [x] update Debian Dockerfile to install package
- [x] update readme for runtime dependencies

**Comment by GeneMosher** [comment]
The Debian and Raspian (i.e., Debian for the Raspberry Pi) distributions each provide the tzdata packages.  Ubuntu is, of course, derived from Debian.

**Comment by NeroBurner** [comment]
CI fixed by PR https://github.com/ViewTouch/viewtouch/pull/59

**Comment by NeroBurner** [comment]
fixed building wiki entry https://github.com/ViewTouch/viewtouch/wiki/Building
