### ISSUE TITLE
Version-info from cmake

### ISSUE THREAD

**Issue by NeroBurner** [ViewTouch/viewtouch#68]
I'm working on a PR to get some more versioning information into the ViewTouch binary

The examples have a short version, a long version and a detailed version info each.
The major, minor and patch number are hard coded in `version.cmake`. The fourth number is the number of commits since the last git tag.

version when no git repo is found or no git executable is found. The timestamp is the current UTC time
```
ViewTouch 4.2.79
ViewTouch 4.2.79-~+dev+dirty
ViewTouch 4.2.79-~+dev+dirty (dirty (detached, dirty), x86_64-linux-gcc8.2.1, 2018-10-22 21:18:24 +0000)
```

version when there are changes in the git repository (git repo is dirty), The timestamp is the current UTC time.
```
ViewTouch 4.2.79
ViewTouch 4.2.79-301+dev+1be90a8
ViewTouch 4.2.79-301+dev+1be90a8 (1be90a8 (nb_dev, dirty), x86_64-linux-gcc8.2.1, 2018-10-22 21:19:59 +0000)
```

version info on a branch (`nb_dev` in this case), clean git repo. The timestamp is the time the current git commit has been commited
```
ViewTouch 4.2.79
ViewTouch 4.2.79-301+dev+1be90a8
ViewTouch 4.2.79-301+dev+1be90a8 (1be90a8 (nb_dev), x86_64-linux-gcc8.2.1, 2018-10-22 23:07:04 +0200)
```

Version info on a git tag `v4.2.79-rc1`. Can be used for releases and release candidates. The timestamp is the time the current git commit has been commited
```
ViewTouch 4.2.79
ViewTouch 4.2.79-0+rc1+c013f47
ViewTouch 4.2.79-0+rc1+c013f47 (c013f47, x86_64-linux-gcc8.2.1, 2018-10-22 23:22:33 +0200)
```

Version info on a git tag `v4.2.79`. Can be used to mark releases. The timestamp is the time the current git commit has been commited
```
ViewTouch 4.2.79
ViewTouch 4.2.79-0+c013f47
ViewTouch 4.2.79-0+c013f47 (x86_64-linux-gcc8.2.1, 2018-10-22 23:22:33 +0200)
```

Is the Versioning scheme acceptable? If yes where should we use which version string?

**Comment by GeneMosher** [comment]
You know, I'm used to seeing the date at the lower left corner which represents the date on which the version on the local machine was compiled.  I'd like to see that continued.  But that's not a version number, and as far as this goes, I'm very comfortable with your judgment on this, perhaps showing the version number and the local compile date.

**Comment by NeroBurner** [comment]
I think the time of the commit says more about the version that is run than the compile time of the build. For development the latest compile time will still be shown instead of the latest commit time

I havn't checked this claim, but I think with the commit time the build could even be a reproducible build https://wiki.debian.org/ReproducibleBuilds

I'd like to have a way in ViewTouch to view all the Info about the currently run binary. Something like a `About` page. Unfortunately I have no Idea where to put what info, and what info the user is interested in ^^

**Comment by NeroBurner** [comment]
![image](https://user-images.githubusercontent.com/9076163/51643046-8089ff80-1f6b-11e9-800f-2b29e8a91a17.png)

new versioning scheme with YY.MM.X-GIT_COUNT. The new example shows the extended version and the date of the commit used to compile the version of viewtouch running

With this change the version number gives a rough estimate of when the version was released, the GIT_COUNT is a increasing number, which grows with every commit, and the date of the commit is always nice to have. The date of the commit can change to date of compilation if the viewtouch source files are modified

**Comment by GeneMosher** [comment]
Very satisfied with this reworking of the Version Information.  The use of various text color(s) to distinguish its various informational component(s) might be appropriate.  This is a very well thought out and useful enhancement for us all !

**Comment by NeroBurner** [comment]
thanks a lot :)
colors would be nice, but are not high on my priority list
