### ISSUE TITLE
Project needs more documentation - How to get it running on server and clients

### ISSUE THREAD

**Issue by thomasfrivold** [ViewTouch/viewtouch#7]
Project needs more documentation - How to get it running on server and clients

How does one compile the program
How does one start the server engine. 
What does the server engine do? 
What ports does it operate? 
What are the dependencies?
The graphics files - Where are they?

**Comment by GeneMosher** [comment]
On 05/12/2015 10:34 PM, thomasfrivold wrote:
>
> Project needs more documentation - How to get it running on server and
> clients
>
We are working on this and your help is something I very much
appreciate.  If you visit the ViewTouch Build page you can see what
we've done so far in that aspect.
>
> How does one compile the program
>
https://github.com/ViewTouch/viewtouch/wiki/Building
>
> How does one start the server engine.
> What does the server engine do?
> What ports does it operate?
>
X typically uses port 6000 while the printers typically use port 9100. 
I will soon be doing a howto for printing.  We use CUPS for that.
>
> What are the dependencies?
> The graphics files - Where are they?
>
The link for these is on the 'Build Page' shown above.  At ViewTouch the
link, just made available yesterday, is
http://www.viewtouch.com/download.html

Thank you for all you've done so far, Thomas.

**Comment by st1nga** [comment]
Yeah, I have no idea how to make it work at the moment I just have a black screen with please wait.

**Comment by Goofybud16** [comment]
@st1nga 

>Yeah, I have no idea how to make it work at the moment I just have a black screen with please wait.

If I remember correctly, that means you are missing the graphical files.

@GeneMosher 

>http://www.viewtouch.com/download.html

I don't see a link for the Graphical Data files there, just for the Android app, the Easy Installer, the PDF, and the installer.

**Comment by GeneMosher** [comment]
This problem has been fixed; the vt_data file with its System Pages is now automatically downloaded from the ViewTouch web site if ViewTouch finds it to be missing when ViewTouch runs.

**Comment by milkboy007** [comment]
i manage to get it running but i cant seem to find any information current user after building, how to add users, or other back end functions. still needs more documentations. a good POS, but not a good opensource POS. lacks a lot of documentations. cant  find my around it.

**Comment by GeneMosher** [comment]
On 02/04/2016 02:29 PM, milkboy007 wrote:
>
> i manage to get it running but i cant seem to find any information
> current user after building, how to add users, or other back end
> functions. still needs more documentations. a good POS, but not a good
> opensource POS. lacks a lot of documentations. cant find my around it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ViewTouch/viewtouch/issues/7#issuecomment-180080612>.
>
What I typically do is to provide a few hours of personal training on
the phone to introduce someone to all the features.  If you would use
your name and give me a call at 541-485-9235 I would be glad to schedule
you in and do this for you, too.  If you are going to use this in a real
situation it would be foolish for you to try to do so without some
assistance.  POS is very serious software and you are being very
premature to judge it.  Normally people just buy a computer and are up
and running in just a few hours.  The reason ViewTouch is on GitHub is
to facilitate source code development now that I am not hiring
programmers anymore.  I'm still financing some developers with several
hundred dollars a month and my customers universally agree that
ViewTouch is the best POS they have ever used.

**Comment by milkboy007** [comment]
lolz. i am currently evaluating the software. yes, "POS is very serious software"
im just stating that the is no documentation for administration.
not to sound ungrateful or anything, unlike other open source POS, (like openbravo pos + forks, and others), there is no literature to read on.
will there be any plan for written administration documentation? easier to access for reference.

calling would be a huge inconvenience for both of us, as i live in a different continent/timezone.
is there any recorded video on you previous trainings? i cant write the documentation from it if you have any.

**Comment by thomasfrivold** [comment]
This is pretty silly.

A software package regardless of who has made it and what history it has
needs explicit documentation.
The documentation should
(0) System requirements
(1) Introduction. Who is this software intended for, what problems does it
solve?
(1) How the software is working, what are the "moving parts".
(2) Describe every function of the system available to the user.
Screenshots necessary.
(3) Describe every function of the system available to administrator.
Screenshots necessary.
(4) Describe how to do every task which a regular user will do. Screenshots
necessary.
(5) Describe how to do every task which an administrator will do.
Screenshots necessary.
(6) License
(7) Third party service providers (hosting providers, support providers,
gear providers) can be added here.

The entire documentation needs to be written explicitly. This means that it
should be written without personal quips and without anecdotes and stories.
These are not relevant to a pure documentation, but can be added to the
project homepage and or included in a final chapter if absolutely
necessary. Only the explicit information intended for the transfer of
knowledge is permissible in a quality documentation. The documentation
should be standing on its own two legs and no require interaction with
anyone else in order to bring the software up and running, and using it on
a daily basis.

Best regards,
Thomas

**Comment by st1nga** [comment]
@thomasfrivold 

I agree and I look forward to your documentation! Well volunteered, you seem to know what is needed for good doco. a job I dislike :-)

**Comment by kmwitservices** [comment]
need help - "make" error at 15%.
after downloading clone and then mkdir build I then cd build and cmake without error, I then "make" and this is the output.
`Scanning dependencies of target vtpos
[ 15%] Building CXX object CMakeFiles/vtpos.dir/loader/loader_main.cc.o
/usr/viewtouch/src/viewtouch/loader/loader_main.cc: In function ‘void OpenStatusBox()’:
/usr/viewtouch/src/viewtouch/loader/loader_main.cc:218:44: error: ‘gtk_label_set_xalign’ was not declared in this scope
     gtk_label_set_xalign(GTK_LABEL(label),0);
                                            ^
/usr/viewtouch/src/viewtouch/loader/loader_main.cc:219:44: error: ‘gtk_label_set_yalign’ was not declared in this scope
     gtk_label_set_yalign(GTK_LABEL(label),1);
                                            ^
CMakeFiles/vtpos.dir/build.make:62: recipe for target 'CMakeFiles/vtpos.dir/loader/loader_main.cc.o' failed
make[2]: *** [CMakeFiles/vtpos.dir/loader/loader_main.cc.o] Error 1
CMakeFiles/Makefile2:179: recipe for target 'CMakeFiles/vtpos.dir/all' failed
make[1]: *** [CMakeFiles/vtpos.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`
Please advise? running cmake 3.8.0

**Comment by GeneMosher** [comment]
I do not get an error on X86 but I do get this same error on the Raspberry Pi's ARM architecture.

[ 15%] Building CXX object CMakeFiles/vtpos.dir/loader/loader_main.cc.o
/home/viewtouch/viewtouch/loader/loader_main.cc: In function ‘void OpenStatusBox()’:
/home/viewtouch/viewtouch/loader/loader_main.cc:218:44: error: ‘gtk_label_set_xalign’ was not declared in this scope
     gtk_label_set_xalign(GTK_LABEL(label),0);
                                            ^
/home/viewtouch/viewtouch/loader/loader_main.cc:219:44: error: ‘gtk_label_set_yalign’ was not declared in this scope
     gtk_label_set_yalign(GTK_LABEL(label),1);
                                            ^

**Comment by GeneMosher** [comment]
This error was reported by someone and I have also experienced it, but only on the Raspberry Pi, which is an ARM processor.  I don't experience it on the X86 processor.

[ 15%] Building CXX object CMakeFiles/vtpos.dir/loader/loader_main.cc.o
/home/viewtouch/viewtouch/loader/loader_main.cc: In function ‘void OpenStatusBox()’:
/home/viewtouch/viewtouch/loader/loader_main.cc:218:44: error: ‘gtk_label_set_xalign’ was not declared in this scope
     gtk_label_set_xalign(GTK_LABEL(label),0);
                                            ^
/home/viewtouch/viewtouch/loader/loader_main.cc:219:44: error: ‘gtk_label_set_yalign’ was not declared in this scope
     gtk_label_set_yalign(GTK_LABEL(label),1);
                                            ^

**Comment by kmwitservices** [comment]
My post has been deleted some how.....?
I am that someone and this error is on virtualbox, processor set as automatic, my physical machine is an intel i7....not arm and not installed on Pi3 box which I was going to do but decided VM was better test ground.

**Comment by GeneMosher** [comment]
I deleted it by error and apologize.  Submit it again if you would. 
Preview it first to make sure it is readable.  Put a cr/lf between
paragraphs.  If you can code you can probably figure out and fix the
error easily.  I would do it but I don't code.  If you don't fix it then
I expect Jason or someone else will.  The explanation for fixing it is
in the error message, seems to me.

**Comment by kmwitservices** [comment]
Sorry but I am not a coder....I have paused the VM and will await response.

**Comment by jasonwartell** [comment]
It looks to me like either the GTK+3 libraries are not installed or it is not searching the correct directory to find the libraries (GTK headers that define those functions).

**Comment by jasonwartell** [comment]
I believe I found the issue. The gtk_label_set_xalign (yalign) functions don't exist until GTK version 3.16. I wrote the code on an Ubuntu machine running version 3.18.9 but Debian is only supporting the stable version 3.14.5-1. Debian is currently testing 3.22. I will try to achieve the same output using alternative functions which are supported by 3.14.

**Comment by jasonwartell** [comment]
I just pushed an update that should eliminate the compilation error. Please let me know if there are any more errors that the compiler hadn't gotten to yet - and/or if it fixed the problem. The only difference that you should notice if you had the previous version running is that the status messages will all be center justified in the right half of the logo instead of left justified to the center of the logo.
